
// 1. ANAGRAFICA STUDENTI CONVITTORI
const studenticonvittori = [
    // 1A tot 6
    { cognome: "COMMOD", nome: "Gaia", classe: "1A", room: "218" },
    { cognome: "GASPARD", nome: "Thierry", classe: "1A", room: "105" },
    { cognome: "JANS", nome: "Giada", classe: "1A", room: "203" },
    { cognome: "OBETTI", nome: "Virginia", classe: "1A", room: "203" },
    { cognome: "PETTORALI", nome: "Matilde", classe: "1A", room: "203" },
    { cognome: "ZIGGIOTTO", nome: "Beatrice", classe: "1A", room: "211" },
    // 1B tot 10
    { cognome: "BLANCHET N", nome: "Nadine", classe: "1B", room: "221" },
    { cognome: "BOMBONATO", nome: "Francesco", classe: "1B", room: "104" },
    { cognome: "DATTRINO", nome: "Nicolas", classe: "1B", room: "105" },
    { cognome: "GIOVANDO", nome: "Caterina", classe: "1B", room: "206" },
    { cognome: "LUNARDI", nome: "Filippo", classe: "1B", room: "108" },
    { cognome: "PASCUZZI", nome: "Pietro", classe: "1B", room: "107" },
    { cognome: "POUJOL", nome: "Chiara", classe: "1B", room: "206" },
    { cognome: "QUERIO GIANETTO", nome: "Giorgio", classe: "1B", room: "104" },
    { cognome: "SALVI", nome: "Sophie", classe: "1B", room: "206" },
    { cognome: "SCHIRRU", nome: "Didier Félicien Hervé", classe: "1B", room: "108" },
    { cognome: "VILARDO", nome: "Gabriele", classe: "1B", room: "104" },
    // 1P tot 11
    { cognome: "CHABLOZ", nome: "Annette", classe: "1P", room: "213" },
    { cognome: "DAGOSTINO", nome: "Domenico", classe: "1P", room: "108" },
    { cognome: "FURLAN", nome: "Alessandro", classe: "1P", room: "111" },
    { cognome: "GIOVANNELLI P", nome: "Pietro", classe: "1P", room: "106" },
    { cognome: "GUIZZETTI RINCON", nome: "Francisco Andres", classe: "1P", room: "105" },
    { cognome: "LAI", nome: "Stefano", classe: "1P", room: "106" },
    { cognome: "LAZIER", nome: "Francesco", classe: "1P", room: "106" },
    { cognome: "PAONESSA", nome: "Leonardo", classe: "1P", room: "107" },
    { cognome: "VINCENT", nome: "Thomas", classe: "1P", room: "103" },
    { cognome: "RUSCI DI LUCA", nome: "Greta", classe: "1P", room: "212" },
    { cognome: "SILVANI", nome: "Amelie", classe: "1P", room: "204" },
    // 2A tot 10
    { cognome: "BARAVALLE", nome: "Andrea", classe: "2A", room: "102" },
    { cognome: "BERTOT", nome: "Manuele", classe: "2A", room: "102" },
    { cognome: "BUZZI", nome: "Alessandro", classe: "2A", room: "101" },
    { cognome: "CASTELLANO", nome: "Martina", classe: "2A", room: "204" },
    { cognome: "DA FRE", nome: "Gaia", classe: "2A", room: "207" },
    { cognome: "DE GASPER", nome: "Lara", classe: "2A", room: "207" },
    { cognome: "GARCIA", nome: "Luis Alberto", classe: "2A", room: "118" },
    { cognome: "HERESAZ", nome: "Alyce", classe: "2A", room: "211" },
    { cognome: "PENNARD", nome: "Serena", classe: "2A", room: "211" },
    { cognome: "SAITTA", nome: "Asia", classe: "2A", room: "207" },
    // 2B tot 9
    { cognome: "CHEN", nome: "Michael Jianhao", classe: "2B", room: "109" },
    { cognome: "DELLAQUILA", nome: "Gabriele", classe: "2B", room: "107" },
    { cognome: "DUNAND", nome: "Audrey", classe: "2B", room: "218" },
    { cognome: "GHILARDINI", nome: "Leonardo", classe: "2B", room: "114" },
    { cognome: "MAINO", nome: "Giada", classe: "2B", room: "218" },
    { cognome: "MISERENDINO", nome: "Ludovica", classe: "2B", room: "204" },
    { cognome: "MOUNIM", nome: "Yahya", classe: "2B", room: "109" },
    { cognome: "PEZZOLI", nome: "Niccolò", classe: "2B", room: "101" },
    { cognome: "TACCONE", nome: "Nicholas", classe: "2B", room: "109" },
    // 2P tot 13
    { cognome: "BERRIAD", nome: "Thierry", classe: "2P", room: "121" },
    { cognome: "BERRUTI A", nome: "Andrea", classe: "2P", room: "114" },
    { cognome: "BERRUTI S", nome: "Stefano", classe: "2P", room: "114" },
    { cognome: "CASALICCHIO", nome: "Nahuel", classe: "2P", room: "121" },
    { cognome: "CLERIN", nome: "Pietro", classe: "2P", room: "110" },
    { cognome: "DONZEL", nome: "Elodie", classe: "2P", room: "213" },
    { cognome: "GENS", nome: "Aaron", classe: "2P", room: "102" },
    { cognome: "HERRERA", nome: "Alexander", classe: "2P", room: "115" },
    { cognome: "MONTERO", nome: "Karen", classe: "2P", room: "209" },
    { cognome: "PERRIN", nome: "Annie", classe: "2P", room: "213" },
    { cognome: "STEVENIN", nome: "Joelle", classe: "2P", room: "208" },
    { cognome: "TORTORELLI C", nome: "Carlotta", classe: "2P", room: "209" },
    { cognome: "TORTORELLI G", nome: "Greta", classe: "2P", room: "209" },
    // 3A tot 5
    { cognome: "CATTARINUSSI", nome: "Samuele", classe: "3A", gruppo: "", room:"101", percorso: "🍷" },
    { cognome: "FLORIAN", nome: "Gabriele", classe: "3A", gruppo: "", room:"118", percorso: "🍴" },
    { cognome: "MARANGELO", nome: "Giulio", classe: "3A", gruppo: "", room:"118", percorso: "🍷" },
    { cognome: "PEAQUIN", nome: "Linda", classe: "3A", gruppo: "", room:"214", percorso: "🍷" },
    { cognome: "ZOPPO", nome: "Rodrigue", classe: "3A", gruppo: "", room:"121", percorso: "🍷" },
    // 3B tot 7
    { cognome: "BLANCHET M", nome: "Magalie", classe: "3B", gruppo: "", room:"214", percorso: "🍷" },
    { cognome: "BOGGIA", nome: "Vittoria", classe: "3B", gruppo: "", room:"214", percorso: "🍷" },
    { cognome: "CIRINA", nome: "Lorenzo", classe: "3B", gruppo: "", room:"110", percorso: "🍴" },
    { cognome: "DUBLANC", nome: "Nicole", classe: "3B", gruppo: "", room:"202", percorso: "🍴" },
    { cognome: "GRANATA", nome: "Gabriele", classe: "3B", gruppo: "", room:"110", percorso: "🍷" },
    { cognome: "PRUTEANU", nome: "Mihai Giuliano", classe: "3B", gruppo: "", room:"116", percorso: "🍴" },
    { cognome: "TRIOLO", nome: "Eleonora", classe: "3B", gruppo: "", room:"214", percorso: "🍷" },
    // 3C tot 7
    { cognome: "CELESIA M", nome: "Marta", classe: "3C", gruppo: "", room:"215", percorso: "🍷" },
    { cognome: "COSTABLOZ", nome: "Giorgia", classe: "3C", gruppo: "", room:"202", percorso: "🍷" },
    { cognome: "CUMINO", nome: "Lucia", classe: "3C", gruppo: "", room:"205", percorso: "🍴" },
    { cognome: "EPICOCO", nome: "Angelica", classe: "3C", gruppo: "", room:"205", percorso: "🍷" },
    { cognome: "MERLET", nome: "Cedric", classe: "3C", gruppo: "", room:"113", percorso: "🍷" },
    { cognome: "PALMISANO", nome: "Clarissa", classe: "3C", gruppo: "", room:"202", percorso: "🍷" },
    { cognome: "TARTIN", nome: "Zoe", classe: "3C", gruppo: "", room:"215", percorso: "🍷" },
    // 3P tot 6
    { cognome: "CONSOL", nome: "Gaia", classe: "3P", room: "208", percorso: "🍴" },
    { cognome: "LAGOMARSINI", nome: "Michele", classe: "3P", room: "111", percorso: "🍴" },
    { cognome: "LLESHI", nome: "Gabriele", classe: "3P", room: "115", percorso: "🍷" },
    { cognome: "MARRERO", nome: "Lewis", classe: "3P", room: "115", percorso: "🍷" },
    { cognome: "RONCO", nome: "Angelica", classe: "3P", room: "208", percorso: "🍴" }, 
    { cognome: "TEBANO", nome: "Serena", classe: "3P", room: "212", percorso: "🍴" }, 
    // 4A tot 14
    { cognome: "CHIADO", nome: "Diego", classe: "4A", room: "123", percorso: "🍴" },
    { cognome: "COMIOTTO", nome: "Lucia", classe: "4A", room: "216", percorso: "🍴" },
    { cognome: "CONTA", nome: "Giovanni", classe: "4A", room: "117", percorso: "🍴" },
    { cognome: "CROCE", nome: "Giacomo", classe: "4A", room: "117", percorso: "🍴" },
    { cognome: "DANNA", nome: "Gioele", classe: "4A", room: "119", percorso: "🍴" },
    { cognome: "DI TRIA", nome: "Alice", classe: "4A", room: "220", percorso: "🍷" },
    { cognome: "MANCUSO", nome: "Gaia", classe: "4A", room: "219", percorso: "🍷" },
    { cognome: "MARCIANO", nome: "Alberto", classe: "4A", room: "116", percorso: "🍴" },
    { cognome: "MENALDINO", nome: "Moreno", classe: "4A", room: "113", percorso: "🍴" },
    { cognome: "NAVARRETTA", nome: "Alexis Denis Fabien", classe: "4A", room: "123", percorso: "🍷" },
    { cognome: "OBERTO", nome: "Debora", classe: "4A", room: "210", percorso: "🍷" },
    { cognome: "TAPPELLA", nome: "Luca", classe: "4A", room: "116", percorso: "🍴" },
    { cognome: "TESSARIN", nome: "Sharon", classe: "4A", room: "205", percorso: "🍴" },
    { cognome: "VIOT", nome: "Cecilia", classe: "4A", room: "210", percorso: "🍷" }, 
    // 4B tot 9
    { cognome: "CHESSA", nome: "Samuele", classe: "4B", room: "111", percorso: "🍴" },
    { cognome: "FAVRE", nome: "Emilie", classe: "4B", room: "217", percorso: "🍷" },
    { cognome: "GIOVANNELLI T", nome: "Tommaso", classe: "4B", room: "113", percorso: "🍷" },
    { cognome: "GORREX", nome: "Valerie", classe: "4B", room: "212", percorso: "🍴" },
    { cognome: "HACHEMAOUI", nome: "Slimane Raffaello", classe: "4B", room: "117", percorso: "🍷" },
    { cognome: "MEYNET", nome: "Riccardo", classe: "4B", room: "123", percorso: "🍴" },
    { cognome: "NICOLASI", nome: "Ginevra", classe: "4B", room: "217", percorso: "🍴" },
    { cognome: "SAVELLA", nome: "Ilaria", classe: "4B", room: "210", percorso: "🍷" },
    { cognome: "SERIO", nome: "Federica", classe: "4B", room: "217", percorso: "🍷" }, 
    // 5A tot 12
    { cognome: "CARRUOZZO", nome: "Amalia", classe: "5A", room: "201", percorso: "🍴", gruppo: "G1" },
    { cognome: "CELESIA A", nome: "Alessio", classe: "5A", room: "120", percorso: "🍴", gruppo: "G2" },
    { cognome: "DE GATTIS", nome: "Eleonora", classe: "5A", room: "219", percorso: "🍴", gruppo: "G2" },
    { cognome: "OBERT", nome: "Tommy", classe: "5A", room: "125", percorso: "🍴", gruppo: "G2" },
    { cognome: "PETRIS", nome: "Maurizio", classe: "5A", room: "113", percorso: "🍴", gruppo: "G2" },
    { cognome: "PICCOLI", nome: "Greta", classe: "5A", room: "201", percorso: "🍴", gruppo: "G1" },
    { cognome: "PIGNATELLI", nome: "Maria Vittoria", classe: "5A", room: "201", percorso: "🍴", gruppo: "G1" },
    { cognome: "RASO", nome: "Beatrice", classe: "5A", room: "220", percorso: "🍴", gruppo: "G2" },
    { cognome: "SALVADORI", nome: "Emile", classe: "5A", room: "124", percorso: "🍴", gruppo: "G2" },
    { cognome: "SORRENTI", nome: "Gabriele", classe: "5A", room: "120", percorso: "🍴", gruppo: "G1" },
    { cognome: "VALLOMY", nome: "Etienne", classe: "5A", room: "124", percorso: "🍴", gruppo: "G2" },
    { cognome: "VIGLIANO", nome: "Jacopo", classe: "5A", room: "120", percorso: "🍴", gruppo: "G1" }, 
    // 5B tot 8
    { cognome: "CHREIM", nome: "Khadijé", classe: "5B", room: "221", percorso: "🍷", gruppo: "G1" },
    { cognome: "CORVO", nome: "Filippo", classe: "5B", room: "119", percorso: "🍷", gruppo: "G1" },
    { cognome: "COTTINO", nome: "Jacqueline", classe: "5B", room: "219", percorso: "🍷", gruppo: "G2" },
    { cognome: "KOUROUMA", nome: "Nora", classe: "5B", room: "215", percorso: "🍷", gruppo: "G2" },
    { cognome: "LINTY", nome: "Alys", classe: "5B", room: "216", percorso: "🍷", gruppo: "G1" },
    { cognome: "MARGUERETTAZ", nome: "Greta", classe: "5B", room: "221", percorso: "🍷", gruppo: "G2" },
    { cognome: "MILLERY", nome: "Mathieu", classe: "5B", room: "124", percorso: "🍷", gruppo: "G2" },
    { cognome: "RABAGLIO", nome: "Filippo", classe: "5B", room: "119", percorso: "🍷", gruppo: "G1" }
];
