//Cognome	Nome Classe	gruppo quinte	Regime convittuale	Percorso Sala oppure Cucina//
// 1. ANAGRAFICA STUDENTI SEMICONVITTORI

const studentiesterni = [
// 1A tot 13 ext
{ cognome: "BIDO ESPIRITU", nome: "Miguel Angel", classe: "1A", room: "-" },
{ cognome: "CONTI", nome: "Dominic", classe: "1A", room: "-" },
{ cognome: "DALONZO", nome: "Tommaso", classe: "1A", room: "-" },
{ cognome: "GJETA", nome: "Valentina", classe: "1A", room: "-" },
{ cognome: "GRANATO", nome: "Riccardo", classe: "1A", room: "-" },
{ cognome: "LOIODICE", nome: "Emanuele", classe: "1A", room: "-" },
{ cognome: "LORETI", nome: "Giulia Francesca", classe: "1A", room: "-" },
{ cognome: "MILANO", nome: "Agata", classe: "1A", room: "-" },
{ cognome: "PILLON", nome: "Julie", classe: "1A", room: "-" },
{ cognome: "POPA", nome: "Alessia Ioana", classe: "1A", room: "-" },
{ cognome: "TARAGLIO", nome: "Kian Duncan", classe: "1A", room: "-" },
{ cognome: "TROCCOLI", nome: "Nicolas Nello", classe: "1A", room: "-" },
{ cognome: "VALENTI", nome: "Alessandro", classe: "1A", room: "-" },
// 1B tot 11 ext
{ cognome: "ALBERTAZZI", nome: "Elena", classe: "1B", room: "-" },
{ cognome: "CHATRIAN", nome: "Lauralie", classe: "1B", room: "-" },
{ cognome: "FRANCESCHI", nome: "Elisa", classe: "1B", room: "-" },
{ cognome: "GOGGI", nome: "Simone", classe: "1B", room: "-" },
{ cognome: "HERIN", nome: "Remy", classe: "1B", room: "-" },
{ cognome: "IANNONE", nome: "Mattia", classe: "1B", room: "-" },
{ cognome: "MARTINI", nome: "Ilaria", classe: "1B", room: "-" },
{ cognome: "MATHAMEL", nome: "Iris", classe: "1B", room: "-" },
{ cognome: "PASCUZZI", nome: "Pietro", classe: "1B", room: "-" },
{ cognome: "PIEILLER", nome: "Carole", classe: "1B", room: "-" },
{ cognome: "PORCEILLON", nome: "Thierry", classe: "1B", room: "-" },
// 1P tot 12 ext
{ cognome: "BARBERO", nome: "Gilles", classe: "1P", room: "-" },
{ cognome: "BARBIERI", nome: "Etienne", classe: "1P", room: "-" },
{ cognome: "BOUKHRIS", nome: "Chams Jacopo", classe: "1P", room: "-" },
{ cognome: "CHEVRERE", nome: "Bruno", classe: "1P", room: "-" },
{ cognome: "DE LUCA", nome: "Andrea", classe: "1P", room: "-" },
{ cognome: "DOMINICI", nome: "Manuel", classe: "1P", room: "-" },
{ cognome: "IMPIERI", nome: "Michael", classe: "1P", room: "-" },
{ cognome: "PALACIO FRIAS", nome: "Milka Lisbeth", classe: "1P", room: "-" },
{ cognome: "PRADUROUX", nome: "Mattia", classe: "1P", room: "-" },
{ cognome: "REVIL", nome: "Thierry", classe: "1P", room: "-" },
{ cognome: "VIGNATI", nome: "Matteo", classe: "1P", room: "-" },
{ cognome: "ZHU", nome: "Meng Qi Alice", classe: "1P", room: "-" },
// 2A tot 9 ext
{ cognome: "BETTINELLI", nome: "Noemi", classe: "2A", room: "-" },
{ cognome: "CANNATA", nome: "Morris", classe: "2A", room: "-" },
{ cognome: "CHADEL", nome: "Federico", classe: "2A", room: "-" },
{ cognome: "CREUX", nome: "Margot", classe: "2A", room: "-" },
{ cognome: "GAGLIANO", nome: "Emma", classe: "2A", room: "-" },
{ cognome: "LOI", nome: "Alessandro", classe: "2A", room: "-" },
{ cognome: "MARASCHI", nome: "Beatrice Maria", classe: "2A", room: "-" },
{ cognome: "PAVESE MEYNET", nome: "Edoardo", classe: "2A", room: "-" },
{ cognome: "ROTONI", nome: "Gabriele", classe: "2A", room: "-" },
// 2B tot 10 ext
{ cognome: "BIANCO", nome: "Francesco", classe: "2B", room: "-" },
{ cognome: "CAGNOLA", nome: "Darlisa", classe: "2B", room: "-" },
{ cognome: "CANEPA", nome: "Andrea", classe: "2B", room: "-" },
{ cognome: "CESARO", nome: "Jonathan David", classe: "2B", room: "-" },
{ cognome: "DUCOURTIL", nome: "Hirlan", classe: "2B", room: "-" },
{ cognome: "ENRIETTI", nome: "Aurora", classe: "2B", room: "-" },
{ cognome: "NAPOLI", nome: "Christian", classe: "2B", room: "-" },
{ cognome: "PRIOD", nome: "Monique", classe: "2B", room: "-" },
{ cognome: "PUTIGNANO", nome: "Norma", classe: "2B", room: "-" },
{ cognome: "TREVES", nome: "Martina", classe: "2B", room: "-" },
// 2P tot 9 ext		
{ cognome: "BELDI", nome: "Hiba", classe: "2P", room: "-" },
{ cognome: "BONASERA", nome: "Gioele", classe: "2P", room: "-" },
{ cognome: "DIDONATO", nome: "Samuele", classe: "2P", room: "-" },
{ cognome: "FARCHI", nome: "Bilal", classe: "2P", room: "-" },
{ cognome: "FIORE", nome: "Federico", classe: "2P", room: "-" },
{ cognome: "LACATENA", nome: "Aurora", classe: "2P", room: "-" },
{ cognome: "MORREALE", nome: "Soraya", classe: "2P", room: "-" },
{ cognome: "RIZZI", nome: "Matteo", classe: "2P", room: "-" },
{ cognome: "SPADACCINO", nome: "Marco", classe: "2P", room: "-" },
// 3A tot 15 ext
{ cognome: "BECQUET", nome: "Jacques", classe: "3A", room: "-", percorso: "🍷" },
{ cognome: "BOZON", nome: "Océane", classe: "3A", room: "-", percorso: "🍴" },
{ cognome: "BUSHATI", nome: "Red", classe: "3A", room: "-", percorso: "🍷" },
{ cognome: "CAPPELLO", nome: "Sophia Maria", classe: "3A", room: "-", percorso: "🍴" },
{ cognome: "DOMENICHELLI", nome: "Simone", classe: "3A", room: "-", percorso: "🍷" },
{ cognome: "DROZ", nome: "Cédric", classe: "3A", room: "-", percorso: "🍷" },
{ cognome: "GIOVINAZZO", nome: "Francesco", classe: "3A", room: "-", percorso: "🍷" },
{ cognome: "GJYLI", nome: "Ketlin", classe: "3A", room: "-", percorso: "🍷" },
{ cognome: "HAFDI", nome: "Yassmine", classe: "3A", room: "-", percorso: "🍴" },
{ cognome: "MORETTI", nome: "Pietro", classe: "3A", room: "-", percorso: "🍴" },
{ cognome: "POPA", nome: "Ioana Sofia", classe: "3A", room: "-", percorso: "🍷" },
{ cognome: "STUMBO", nome: "Matteo", classe: "3A", room: "-", percorso: "🍴" },
{ cognome: "TRIESTE", nome: "Fabrizio", classe: "3A", room: "-", percorso: "🍴" },
{ cognome: "VALLET", nome: "Gaelle", classe: "3A", room: "-", percorso: "🍷" },
{ cognome: "VERTHUY", nome: "Aline", classe: "3A", room: "-", percorso: "🍴" },
// 3B tot 11 ext
{ cognome: "BERGER", nome: "Agata", classe: "3B", room: "-", percorso: "🍷" },
{ cognome: "BRACCIOFORTE", nome: "Denise", classe: "3B", room: "-", percorso: "🍷" },
{ cognome: "CHAPPOZ", nome: "Angelo", classe: "3B", room: "-", percorso: "🍴" },
{ cognome: "COSMA", nome: "Evan", classe: "3B", room: "-", percorso: "🍴" },
{ cognome: "DATTOLO", nome: "Jacopo", classe: "3B", room: "-", percorso: "🍷" },
{ cognome: "DORIGO", nome: "Lorenzo", classe: "3B", room: "-", percorso: "🍴" },
{ cognome: "GOUAICHE", nome: "Tarik", classe: "3B", room: "-", percorso: "🍴" },
{ cognome: "JOLY", nome: "Hemile", classe: "3B", room: "-", percorso: "🍴" },
{ cognome: "MENEGATTI", nome: "Alice", classe: "3B", room: "-", percorso: "🍴" },
{ cognome: "MUS", nome: "Alessandro", classe: "3B", room: "-", percorso: "🍴" },
{ cognome: "RUVIDI", nome: "Sofia", classe: "3B", room: "-", percorso: "🍴" },
// 3C tot 10 ext
{ cognome: "AGATI", nome: "Diego", classe: "3C", room: "-", percorso: "🍴" },
{ cognome: "BENIN", nome: "Niccolo", classe: "3C", room: "-", percorso: "🍴" },
{ cognome: "CHIAROTTO", nome: "Samuele", classe: "3C", room: "-", percorso: "🍴" },
{ cognome: "DOCI", nome: "Aldo", classe: "3C", room: "-", percorso: "🍷" },
{ cognome: "FIORITO", nome: "Alessandro", classe: "3C", room: "-", percorso: "🍴" },
{ cognome: "FRACASSO", nome: "Manuel", classe: "3C", room: "-", percorso: "🍷" },
{ cognome: "GJETA", nome: "Anieze", classe: "3C", room: "-", percorso: "🍷" },
{ cognome: "MARTINA", nome: "Giulia", classe: "3C", room: "-", percorso: "🍷" },
{ cognome: "MURACA", nome: "Marco", classe: "3C", room: "-", percorso: "🍴" },
{ cognome: "VITALE", nome: "Nicolas", classe: "3C", room: "-", percorso: "🍷" },
// 3P tot 11 ext
{ cognome: "BARMASSE", nome: "Murielle", classe: "3P", room: "-", percorso: "🍴" },
{ cognome: "BORETTAZ", nome: "Maddalena", classe: "3P", room: "-", percorso: "🍴" },
{ cognome: "BRUNOD", nome: "Gilles", classe: "3P", room: "-", percorso: "🍴" },
{ cognome: "CINA", nome: "Ira", classe: "3P", room: "-", percorso: "🍴" },
{ cognome: "COSTANZA", nome: "Marcello", classe: "3P", room: "-", percorso: "🍴" },
{ cognome: "CRISCI", nome: "Giulia", classe: "3P", room: "-", percorso: "🍷" },
{ cognome: "EZZNADI", nome: "Nissrine", classe: "3P", room: "-", percorso: "🍴" },
{ cognome: "HARZAFI", nome: "Wassim", classe: "3P", room: "-", percorso: "🍴" },
{ cognome: "MODINA", nome: "Elisa", classe: "3P", room: "-", percorso: "🍷" },
{ cognome: "MOSAICO", nome: "Angelo", classe: "3P", room: "-", percorso: "🍴" },
{ cognome: "SPADA", nome: "Alex Armando", classe: "3P", room: "-", percorso: "🍴" },
// 4 A tot 9 ext
{ cognome: "ANGIARI", nome: "Filippo", classe: "4A", room: "-", percorso: "🍴" },
{ cognome: "CANZAN", nome: "Elizabeth", classe: "4A", room: "-", percorso: "🍷" },
{ cognome: "CARUSO", nome: "Isabella", classe: "4A", room: "-", percorso: "🍴" },
{ cognome: "CHIUDINELLI", nome: "Chloé", classe: "4A", room: "-", percorso: "🍷" },
{ cognome: "FARES", nome: "Laura", classe: "4A", room: "-", percorso: "🍴" },
{ cognome: "FREGNANI", nome: "Luisa", classe: "4A", room: "-", percorso: "🍷" },
{ cognome: "LOIODICE", nome: "Daniele", classe: "4A", room: "-", percorso: "🍷" },
{ cognome: "MORABITO", nome: "Tommaso", classe: "4A", room: "-", percorso: "🍷" },
{ cognome: "ZHU", nome: "Fabio Junjie", classe: "4A", room: "-", percorso: "🍷" },
//4B tot 16 ext
{ cognome: "BADERY", nome: "Michelle", classe: "4B", room: "-", percorso: "🍴" },
{ cognome: "CAMPANALE", nome: "Aronne", classe: "4B", room: "-", percorso: "🍷" },
{ cognome: "CHEVRERE", nome: "Cloe", classe: "4B", room: "-", percorso: "🍴" },
{ cognome: "COLLURA", nome: "Asia Francesca", classe: "4B", room: "-", percorso: "🍷" },
{ cognome: "COSTABLOZ", nome: "Giulia", classe: "4B", room: "-", percorso: "🍷" },
{ cognome: "DEPLANO", nome: "Alessandro Antoine Junior", classe: "4B", room: "-", percorso: "🍷" },
{ cognome: "GEMELLO", nome: "Leonardo", classe: "4B", room: "-", percorso: "🍴" },
{ cognome: "GIARDULLO", nome: "Christian", classe: "4B", room: "-", percorso: "🍴" },
{ cognome: "LANTERI", nome: "Paolo", classe: "4B", room: "-", percorso: "🍷" },
{ cognome: "LODATO", nome: "Lorenzo Damiano", classe: "4B", room: "-", percorso: "🍴" },
{ cognome: "MASCARO", nome: "Angelica", classe: "4B", room: "-", percorso: "🍴" },
{ cognome: "MILLESI", nome: "Aline", classe: "4B", room: "-", percorso: "🍷" },
{ cognome: "NIZELLI", nome: "Luca", classe: "4B", room: "-", percorso: "🍴" },
{ cognome: "PRIOD", nome: "Anaïs", classe: "4B", room: "-", percorso: "🍴" },
{ cognome: "VOUT", nome: "Sophie", classe: "4B", room: "-", percorso: "🍷" },
{ cognome: "VUILLERMOZ", nome: "Asia", classe: "4B", room: "-", percorso: "🍷" },
// 5A tot 12 ext
{ cognome: "AGOSTINO", nome: "Thomas", classe: "5A", room: "-", percorso: "🍴", gruppo: "G2" },
{ cognome: "BERNARDI", nome: "Caterina", classe: "5A", room: "-", percorso: "🍴", gruppo: "G2" },
{ cognome: "BORRA", nome: "Yader", classe: "5A", room: "-", percorso: "🍴", gruppo: "G1" },
{ cognome: "CHIALE", nome: "Alessio", classe: "5A", room: "-", percorso: "🍴", gruppo: "G2" },
{ cognome: "FARINET", nome: "Luca", classe: "5A", room: "-", percorso: "🍴", gruppo: "G2" },
{ cognome: "FORESTIERO", nome: "Simone", classe: "5A", room: "-", percorso: "🍴", gruppo: "G1" },
{ cognome: "FOUDON", nome: "Emil", classe: "5A", room: "-", percorso: "🍴", gruppo: "G1" },
{ cognome: "GLAVINAZ", nome: "Pierre", classe: "5A", room: "-", percorso: "🍴", gruppo: "G2" },
{ cognome: "JOLY", nome: "Simone", classe: "5A", room: "-", percorso: "🍴", gruppo: "G1" },
{ cognome: "MARASCO", nome: "Teresa", classe: "5A", room: "-", percorso: "🍴", gruppo: "G1" },
{ cognome: "MARTINOD", nome: "Gabriel", classe: "5A", room: "-", percorso: "🍴", gruppo: "G1" },
{ cognome: "SPALLA", nome: "Giovanni", classe: "5A", room: "-", percorso: "🍴", gruppo: "G1" },
// 5B tot 8 ext
{ cognome: "CARRUOZZO", nome: "Virginia", classe: "5B", room: "-", percorso: "🍷", gruppo: "G2" },
{ cognome: "DORIGO", nome: "Lisa", classe: "5B", room: "-", percorso: "🍷", gruppo: "G1" },
{ cognome: "HU", nome: "Jia Hao", classe: "5B", room: "-", percorso: "🍷", gruppo: "G2" },
{ cognome: "JOLY", nome: "Daiana", classe: "5B", room: "-", percorso: "🍷", gruppo: "G1" },
{ cognome: "PERNET", nome: "Pietro", classe: "5B", room: "-", percorso: "🍷", gruppo: "G1" },
{ cognome: "SECCO", nome: "Sofia", classe: "5B", room: "-", percorso: "🍷", gruppo: "G2" },
{ cognome: "TAVERNA", nome: "Marta", classe: "5B", room: "-", percorso: "🍷", gruppo: "G1" },
{ cognome: "TOMASELLA", nome: "Vittorio", classe: "5B", room: "-", percorso: "🍷", gruppo: "G2" },

];
