/* STUDENTI_25-26.JS 
 * elenco completo a.a. 2025
 */

const tuttiStudenti = [
    // Classe 1A
    { id: 1, cognome: "BIDO ESPIRITU", nome: "Miguel Angel", classe: "1A", room: "-" },
    { id: 2, cognome: "COMMOD", nome: "Gaia", classe: "1A", room: "218" },
    { id: 3, cognome: "CONTI", nome: "Dominic", classe: "1A", room: "-" },
    { id: 4, cognome: "DALONZO", nome: "Tommaso", classe: "1A", room: "-" },
    { id: 5, cognome: "GASPARD", nome: "Thierry", classe: "1A", room: "105" },
    { id: 6, cognome: "GJETA", nome: "Valentina", classe: "1A", room: "-" },
    { id: 7, cognome: "GRANATO", nome: "Riccardo", classe: "1A", room: "-" },
    { id: 8, cognome: "JANS", nome: "Giada", classe: "1A", room: "203" },
    { id: 9, cognome: "LOIODICE", nome: "Emanuele", classe: "1A", room: "-" },
    { id: 10, cognome: "LORETI", nome: "Giulia Francesca", classe: "1A", room: "-" },
    { id: 11, cognome: "MILANO", nome: "Agata", classe: "1A", room: "-" },
    { id: 12, cognome: "OBETTI", nome: "Virginia", classe: "1A", room: "203" },
    { id: 13, cognome: "PETTORALI", nome: "Matilde", classe: "1A", room: "203" },
    { id: 14, cognome: "PILLON", nome: "Julie", classe: "1A", room: "-" },
    { id: 15, cognome: "POPA", nome: "Alessia Ioana", classe: "1A", room: "-" },
    { id: 16, cognome: "TARAGLIO", nome: "Kian Duncan", classe: "1A", room: "-" },
    { id: 17, cognome: "TROCCOLI", nome: "Nicolas Nello", classe: "1A", room: "-" },
    { id: 18, cognome: "VALENTI", nome: "Alessandro", classe: "1A", room: "-" },
    { id: 19, cognome: "ZIGGIOTTO", nome: "Beatrice", classe: "1A", room: "211" },

    // Classe 1B
    { id: 20, cognome: "ALBERTAZZI", nome: "Elena", classe: "1B", room: "-" },
    { id: 21, cognome: "BLANCHET N", nome: "Nadine", classe: "1B", room: "206" },
    { id: 22, cognome: "BOMBONATO", nome: "Francesco", classe: "1B", room: "104" },
    { id: 23, cognome: "CHATRIAN", nome: "Lauralie", classe: "1B", room: "-" },
    { id: 24, cognome: "DATTRINO", nome: "Nicolas", classe: "1B", room: "105" },
    { id: 25, cognome: "FRANCESCHI", nome: "Elisa", classe: "1B", room: "-" },
    { id: 26, cognome: "GIOVANDO", nome: "Caterina", classe: "1B", room: "221" },
    { id: 27, cognome: "GOGGI", nome: "Simone", classe: "1B", room: "-" },
    { id: 28, cognome: "HERIN", nome: "Remy", classe: "1B", room: "-" },
    { id: 29, cognome: "IANNONE", nome: "Mattia", classe: "1B", room: "-" },
    { id: 30, cognome: "LUNARDI", nome: "Filippo", classe: "1B", room: "108" },
    { id: 31, cognome: "MARTINI", nome: "Ilaria", classe: "1B", room: "-" },
    { id: 32, cognome: "MATHAMEL", nome: "Iris", classe: "1B", room: "-" },
    { id: 33, cognome: "PASCUZZI", nome: "Pietro", classe: "1B", room: "107" },
    { id: 34, cognome: "PIEILLER", nome: "Carole", classe: "1B", room: "-" },
    { id: 35, cognome: "PORCEILLON", nome: "Thierry", classe: "1B", room: "-" },
    { id: 36, cognome: "POUJOL", nome: "Chiara", classe: "1B", room: "206" },
    { id: 37, cognome: "QUERIO GIANETTO", nome: "Giorgio", classe: "1B", room: "104" },
    { id: 38, cognome: "SALVI", nome: "Sophie", classe: "1B", room: "206" },
    { id: 39, cognome: "SCHIRRU", nome: "Didier Félicien Hervé", classe: "1B", room: "108" },
    { id: 40, cognome: "VILARDO", nome: "Gabriele", classe: "1B", room: "104" },

    // Classe 1P
    { id: 41, cognome: "BARBERO", nome: "Gilles", classe: "1P", room: "-" },
    { id: 42, cognome: "BARBIERI", nome: "Etienne", classe: "1P", room: "-" },
    { id: 43, cognome: "BOUKHRIS", nome: "Chams Jacopo", classe: "1P", room: "-" },
    { id: 44, cognome: "CHABLOZ", nome: "Annette", classe: "1P", room: "213" },
    { id: 45, cognome: "CHEVRERE", nome: "Bruno", classe: "1P", room: "-" },
    { id: 46, cognome: "DAGOSTINO", nome: "Domenico", classe: "1P", room: "108" },
    { id: 47, cognome: "DE LUCA", nome: "Andrea", classe: "1P", room: "-" },
    { id: 48, cognome: "DOMINICI", nome: "Manuel", classe: "1P", room: "-" },
    { id: 49, cognome: "FURLAN", nome: "Alessandro", classe: "1P", room: "111" },
    { id: 50, cognome: "GIOVANNELLI P", nome: "Pietro", classe: "1P", room: "106" },
    { id: 51, cognome: "GUIZZETTI RINCON", nome: "Francisco Andres", classe: "1P", room: "105" },
    { id: 52, cognome: "IMPIERI", nome: "Michael", classe: "1P", room: "-" },
    { id: 53, cognome: "LAI", nome: "Stefano", classe: "1P", room: "106" },
    { id: 54, cognome: "LAZIER", nome: "Francesco", classe: "1P", room: "106" },
    { id: 55, cognome: "PALACIO FRIAS", nome: "Milka Lisbeth", classe: "1P", room: "-" },
    { id: 56, cognome: "PAONESSA", nome: "Leonardo", classe: "1P", room: "107" },
    { id: 57, cognome: "PRADUROUX", nome: "Mattia", classe: "1P", room: "-" },
    { id: 58, cognome: "REVIL", nome: "Thierry", classe: "1P", room: "-" },
    { id: 59, cognome: "RUSCI DI LUCA", nome: "Greta", classe: "1P", room: "212" },
    { id: 60, cognome: "SILVANI", nome: "Amelie", classe: "1P", room: "204" },
    { id: 61, cognome: "VIGNATI", nome: "Matteo", classe: "1P", room: "-" },
    { id: 62, cognome: "VINCENT", nome: "Thomas", classe: "1P", room: "103" },
    { id: 63, cognome: "ZHU", nome: "Meng Qi Alice", classe: "1P", room: "-" },

    // Classe 2A
    { id: 64, cognome: "BARAVALLE", nome: "Andrea", classe: "2A", room: "102" },
    { id: 65, cognome: "BERTOT", nome: "Manuele", classe: "2A", room: "102" },
    { id: 66, cognome: "BETTINELLI", nome: "Noemi", classe: "2A", room: "-" },
    { id: 67, cognome: "BUZZI", nome: "Alessandro", classe: "2A", room: "101" },
    { id: 68, cognome: "CANNATA", nome: "Morris", classe: "2A", room: "-" },
    { id: 69, cognome: "CASTELLANO", nome: "Martina", classe: "2A", room: "204" },
    { id: 70, cognome: "CHADEL", nome: "Federico", classe: "2A", room: "-" },
    { id: 71, cognome: "CREUX", nome: "Margot", classe: "2A", room: "-" },
    { id: 72, cognome: "DA FRE", nome: "Gaia", classe: "2A", room: "207" },
    { id: 73, cognome: "DE GASPER", nome: "Lara", classe: "2A", room: "207" },
    { id: 74, cognome: "GAGLIANO", nome: "Emma", classe: "2A", room: "-" },
    { id: 75, cognome: "GARCIA", nome: "Luis Alberto", classe: "2A", room: "118" },
    { id: 76, cognome: "HERESAZ", nome: "Alyce", classe: "2A", room: "211" },
    { id: 77, cognome: "LOI", nome: "Alessandro", classe: "2A", room: "-" },
    { id: 78, cognome: "MARASCHI", nome: "Beatrice Maria", classe: "2A", room: "-" },
    { id: 79, cognome: "PAVESE MEYNET", nome: "Edoardo", classe: "2A", room: "-" },
    { id: 80, cognome: "PENNARD", nome: "Serena", classe: "2A", room: "211" },
    { id: 81, cognome: "ROTONI", nome: "Gabriele", classe: "2A", room: "-" },
    { id: 82, cognome: "SAITTA", nome: "Asia", classe: "2A", room: "207" },

    // Classe 2B
    { id: 83, cognome: "BIANCO", nome: "Francesco", classe: "2B", room: "-" },
    { id: 84, cognome: "CAGNOLA", nome: "Darlisa", classe: "2B", room: "-" },
    { id: 85, cognome: "CANEPA", nome: "Andrea", classe: "2B", room: "-" },
    { id: 86, cognome: "CESARO", nome: "Jonathan David", classe: "2B", room: "-" },
    { id: 87, cognome: "CHEN", nome: "Michael Jianhao", classe: "2B", room: "109" },
    { id: 88, cognome: "DELLAQUILA", nome: "Gabriele", classe: "2B", room: "107" },
    { id: 89, cognome: "DUCOURTIL", nome: "Hirlan", classe: "2B", room: "-" },
    { id: 90, cognome: "DUNAND", nome: "Audrey", classe: "2B", room: "218" },
    { id: 91, cognome: "ENRIETTI", nome: "Aurora", classe: "2B", room: "-" },
    { id: 92, cognome: "GHILARDINI", nome: "Leonardo", classe: "2B", room: "114" },
    { id: 93, cognome: "MAINO", nome: "Giada", classe: "2B", room: "218" },
    { id: 94, cognome: "MISERENDINO", nome: "Ludovica", classe: "2B", room: "204" },
    { id: 95, cognome: "MOUNIM", nome: "Yahya", classe: "2B", room: "109" },
    { id: 96, cognome: "NAPOLI", nome: "Christian", classe: "2B", room: "-" },
    { id: 97, cognome: "PEZZOLI", nome: "Niccolò", classe: "2B", room: "101" },
    { id: 98, cognome: "PRIOD", nome: "Monique", classe: "2B", room: "-" },
    { id: 99, cognome: "PUTIGNANO", nome: "Norma", classe: "2B", room: "-" },
    { id: 100, cognome: "TACCONE", nome: "Nicholas", classe: "2B", room: "109" },
    { id: 101, cognome: "TREVES", nome: "Martina", classe: "2B", room: "-" },

    // Classe 2P
    { id: 102, cognome: "BELDI", nome: "Hiba", classe: "2P", room: "-" },
    { id: 103, cognome: "BERRIAD", nome: "Thierry", classe: "2P", room: "121" },
    { id: 104, cognome: "BERRUTI A", nome: "Andrea", classe: "2P", room: "114" },
    { id: 105, cognome: "BERRUTI S", nome: "Stefano", classe: "2P", room: "114" },
    { id: 106, cognome: "BONASERA", nome: "Gioele", classe: "2P", room: "-" },
    { id: 107, cognome: "CASALICCHIO", nome: "Nahuel", classe: "2P", room: "121" },
    { id: 108, cognome: "CLERIN", nome: "Pietro", classe: "2P", room: "110" },
    { id: 109, cognome: "DIDONATO", nome: "Samuele", classe: "2P", room: "-" },
    { id: 110, cognome: "DONZEL", nome: "Elodie", classe: "2P", room: "213" },
    { id: 111, cognome: "FARCHI", nome: "Bilal", classe: "2P", room: "-" },
    { id: 112, cognome: "FIORE", nome: "Federico", classe: "2P", room: "-" },
    { id: 113, cognome: "GENS", nome: "Aaron", classe: "2P", room: "102" },
    { id: 114, cognome: "HERRERA", nome: "Alexander", classe: "2P", room: "115" },
    { id: 115, cognome: "LACATENA", nome: "Aurora", classe: "2P", room: "-" },
    { id: 116, cognome: "MONTERO", nome: "Karen", classe: "2P", room: "209" },
    { id: 117, cognome: "MORREALE", nome: "Soraya", classe: "2P", room: "-" },
    { id: 118, cognome: "PERRIN", nome: "Annie", classe: "2P", room: "213" },
    { id: 119, cognome: "RIZZI", nome: "Matteo", classe: "2P", room: "-" },
    { id: 120, cognome: "SPADACCINO", nome: "Marco", classe: "2P", room: "-" },
    { id: 121, cognome: "STEVENIN", nome: "Joelle", classe: "2P", room: "208" },
    { id: 122, cognome: "TORTORELLI C", nome: "Carlotta", classe: "2P", room: "209" },
    { id: 123, cognome: "TORTORELLI G", nome: "Greta", classe: "2P", room: "209" },

    // Classe 3A
    { id: 124, cognome: "BECQUET", nome: "Jacques", classe: "3A", room: "-", percorso: "🍷" },
    { id: 125, cognome: "BOZON", nome: "Océane", classe: "3A", room: "-", percorso: "🍴" },
    { id: 126, cognome: "BUSHATI", nome: "Red", classe: "3A", room: "-", percorso: "🍷" },
    { id: 127, cognome: "CAPPELLO", nome: "Sophia Maria", classe: "3A", room: "-", percorso: "🍴" },
    { id: 128, cognome: "CATTARINUSSI", nome: "Samuele", classe: "3A", gruppo: "", room: "101", percorso: "🍷" },
    { id: 129, cognome: "DOMENICHELLI", nome: "Simone", classe: "3A", room: "-", percorso: "🍷" },
    { id: 130, cognome: "DROZ", nome: "Cédric", classe: "3A", room: "-", percorso: "🍷" },
    { id: 131, cognome: "FLORIAN", nome: "Gabriele", classe: "3A", gruppo: "", room: "118", percorso: "🍴" },
    { id: 132, cognome: "GIOVINAZZO", nome: "Francesco", classe: "3A", room: "-", percorso: "🍷" },
    { id: 133, cognome: "GJYLI", nome: "Ketlin", classe: "3A", room: "-", percorso: "🍷" },
    { id: 134, cognome: "HAFDI", nome: "Yassmine", classe: "3A", room: "-", percorso: "🍴" },
    { id: 135, cognome: "MARANGELO", nome: "Giulio", classe: "3A", gruppo: "", room: "118", percorso: "🍷" },
    { id: 136, cognome: "MORETTI", nome: "Pietro", classe: "3A", room: "-", percorso: "🍴" },
    { id: 137, cognome: "PEAQUIN", nome: "Linda", classe: "3A", gruppo: "", room: "214", percorso: "🍷" },
    { id: 138, cognome: "POPA", nome: "Ioana Sofia", classe: "3A", room: "-", percorso: "🍷" },
    { id: 139, cognome: "STUMBO", nome: "Matteo", classe: "3A", room: "-", percorso: "🍴" },
    { id: 140, cognome: "TRIESTE", nome: "Fabrizio", classe: "3A", room: "-", percorso: "🍴" },
    { id: 141, cognome: "VALLET", nome: "Gaelle", classe: "3A", room: "-", percorso: "🍷" },
    { id: 142, cognome: "VERTHUY", nome: "Aline", classe: "3A", room: "-", percorso: "🍴" },
    { id: 143, cognome: "ZOPPO", nome: "Rodrigue", classe: "3A", gruppo: "", room: "125", percorso: "🍷" },

    // Classe 3B
    { id: 144, cognome: "BERGER", nome: "Agata", classe: "3B", room: "-", percorso: "🍷" },
    { id: 145, cognome: "BLANCHET M", nome: "Magalie", classe: "3B", gruppo: "", room: "214", percorso: "🍷" },
    { id: 146, cognome: "BOGGIA", nome: "Vittoria", classe: "3B", gruppo: "", room: "214", percorso: "🍷" },
    { id: 147, cognome: "BRACCIOFORTE", nome: "Denise", classe: "3B", room: "-", percorso: "🍷" },
    { id: 148, cognome: "CHAPPOZ", nome: "Angelo", classe: "3B", room: "-", percorso: "🍴" },
    { id: 149, cognome: "CIRINA", nome: "Lorenzo", classe: "3B", gruppo: "", room: "110", percorso: "🍴" },
    { id: 150, cognome: "COSMA", nome: "Evan", classe: "3B", room: "-", percorso: "🍴" },
    { id: 151, cognome: "DATTOLO", nome: "Jacopo", classe: "3B", room: "-", percorso: "🍷" },
    { id: 152, cognome: "DORIGO", nome: "Lorenzo", classe: "3B", room: "-", percorso: "🍴" },
    { id: 153, cognome: "DUBLANC", nome: "Nicole", classe: "3B", gruppo: "", room: "202", percorso: "🍴" },
    { id: 154, cognome: "GOUAICHE", nome: "Tarik", classe: "3B", room: "-", percorso: "🍴" },
    { id: 155, cognome: "GRANATA", nome: "Gabriele", classe: "3B", gruppo: "", room: "110", percorso: "🍷" },
    { id: 156, cognome: "JOLY", nome: "Hemile", classe: "3B", room: "-", percorso: "🍴" },
    { id: 157, cognome: "MENEGATTI", nome: "Alice", classe: "3B", room: "-", percorso: "🍴" },
    { id: 158, cognome: "MUS", nome: "Alessandro", classe: "3B", room: "-", percorso: "🍴" },
    { id: 159, cognome: "PRUTEANU", nome: "Mihai Giuliano", classe: "3B", gruppo: "", room: "116", percorso: "🍴" },
    { id: 160, cognome: "RUVIDI", nome: "Sofia", classe: "3B", room: "-", percorso: "🍴" },
    { id: 161, cognome: "TRIOLO", nome: "Eleonora", classe: "3B", gruppo: "", room: "214", percorso: "🍷" },

    // Classe 3C
    { id: 162, cognome: "AGATI", nome: "Diego", classe: "3C", room: "-", percorso: "🍴" },
    { id: 163, cognome: "BENIN", nome: "Niccolo", classe: "3C", room: "-", percorso: "🍴" },
    { id: 164, cognome: "CELESIA M", nome: "Marta", classe: "3C", gruppo: "", room: "215", percorso: "🍷" },
    { id: 165, cognome: "CHIAROTTO", nome: "Samuele", classe: "3C", room: "-", percorso: "🍴" },
    { id: 166, cognome: "COSTABLOZ", nome: "Giorgia", classe: "3C", gruppo: "", room: "202", percorso: "🍷" },
    { id: 167, cognome: "CUMINO", nome: "Lucia", classe: "3C", gruppo: "", room: "205", percorso: "🍴" },
    { id: 168, cognome: "DOCI", nome: "Aldo", classe: "3C", room: "-", percorso: "🍷" },
    { id: 169, cognome: "EPICOCO", nome: "Angelica", classe: "3C", gruppo: "", room: "205", percorso: "🍷" },
    { id: 170, cognome: "FIORITO", nome: "Alessandro", classe: "3C", room: "-", percorso: "🍴" },
    { id: 171, cognome: "FRACASSO", nome: "Manuel", classe: "3C", room: "-", percorso: "🍷" },
    { id: 172, cognome: "GJETA", nome: "Anieze", classe: "3C", room: "-", percorso: "🍷" },
    { id: 173, cognome: "MARTINA", nome: "Giulia", classe: "3C", room: "-", percorso: "🍷" },
    { id: 174, cognome: "MERLET", nome: "Cedric", classe: "3C", gruppo: "", room: "113", percorso: "🍷" },
    { id: 175, cognome: "MURACA", nome: "Marco", classe: "3C", room: "-", percorso: "🍴" },
    { id: 176, cognome: "PALMISANO", nome: "Clarissa", classe: "3C", gruppo: "", room: "202", percorso: "🍷" },
    { id: 177, cognome: "TARTIN", nome: "Zoe", classe: "3C", gruppo: "", room: "215", percorso: "🍷" },
    { id: 178, cognome: "VITALE", nome: "Nicolas", classe: "3C", room: "-", percorso: "🍷" },

    // Classe 3P
    { id: 179, cognome: "BARMASSE", nome: "Murielle", classe: "3P", room: "-", percorso: "🍴" },
    { id: 180, cognome: "BORETTAZ", nome: "Maddalena", classe: "3P", room: "-", percorso: "🍴" },
    { id: 181, cognome: "BRUNOD", nome: "Gilles", classe: "3P", room: "-", percorso: "🍴" },
    { id: 182, cognome: "CINA", nome: "Ira", classe: "3P", room: "-", percorso: "🍴" },
    { id: 183, cognome: "CONSOL", nome: "Gaia", classe: "3P", room: "208", percorso: "🍴" },
    { id: 184, cognome: "COSTANZA", nome: "Marcello", classe: "3P", room: "-", percorso: "🍴" },
    { id: 185, cognome: "CRISCI", nome: "Giulia", classe: "3P", room: "-", percorso: "🍷" },
    { id: 186, cognome: "EZZNADI", nome: "Nissrine", classe: "3P", room: "-", percorso: "🍴" },
    { id: 187, cognome: "HARZAFI", nome: "Wassim", classe: "3P", room: "-", percorso: "🍴" },
    { id: 188, cognome: "LAGOMARSINI", nome: "Michele", classe: "3P", room: "111", percorso: "🍴" },
    { id: 189, cognome: "LLESHI", nome: "Gabriele", classe: "3P", room: "115", percorso: "🍷" },
    { id: 190, cognome: "MARRERO", nome: "Lewis", classe: "3P", room: "115", percorso: "🍷" },
    { id: 191, cognome: "MODINA", nome: "Elisa", classe: "3P", room: "-", percorso: "🍷" },
    { id: 192, cognome: "MOSAICO", nome: "Angelo", classe: "3P", room: "-", percorso: "🍴" },
    { id: 193, cognome: "RONCO", nome: "Angelica", classe: "3P", room: "208", percorso: "🍴" },
    { id: 194, cognome: "SPADA", nome: "Alex Armando", classe: "3P", room: "-", percorso: "🍴" },
    { id: 195, cognome: "TEBANO", nome: "Serena", classe: "3P", room: "212", percorso: "🍴" },

    // Classe 4A
    { id: 196, cognome: "ANGIARI", nome: "Filippo", classe: "4A", room: "-", percorso: "🍴" },
    { id: 197, cognome: "CANZAN", nome: "Elizabeth", classe: "4A", room: "-", percorso: "🍷" },
    { id: 198, cognome: "CARUSO", nome: "Isabella", classe: "4A", room: "-", percorso: "🍴" },
    { id: 199, cognome: "CHIADO", nome: "Diego", classe: "4A", room: "123", percorso: "🍴" },
    { id: 200, cognome: "CHIUDINELLI", nome: "Chloé", classe: "4A", room: "-", percorso: "🍷" },
    { id: 201, cognome: "COMIOTTO", nome: "Lucia", classe: "4A", room: "216", percorso: "🍴" },
    { id: 202, cognome: "CONTA", nome: "Giovanni", classe: "4A", room: "117", percorso: "🍴" },
    { id: 203, cognome: "CROCE", nome: "Giacomo", classe: "4A", room: "117", percorso: "🍴" },
    { id: 204, cognome: "DANNA", nome: "Gioele", classe: "4A", room: "119", percorso: "🍴" },
    { id: 205, cognome: "DI TRIA", nome: "Alice", classe: "4A", room: "220", percorso: "🍷" },
    { id: 206, cognome: "FARES", nome: "Laura", classe: "4A", room: "-", percorso: "🍴" },
    { id: 207, cognome: "FREGNANI", nome: "Luisa", classe: "4A", room: "-", percorso: "🍷" },
    { id: 208, cognome: "LOIODICE", nome: "Daniele", classe: "4A", room: "-", percorso: "🍷" },
    { id: 209, cognome: "MANCUSO", nome: "Gaia", classe: "4A", room: "219", percorso: "🍷" },
    { id: 210, cognome: "MARCIANO", nome: "Alberto", classe: "4A", room: "116", percorso: "🍴" },
    { id: 211, cognome: "MENALDINO", nome: "Moreno", classe: "4A", room: "113", percorso: "🍴" },
    { id: 212, cognome: "MORABITO", nome: "Tommaso", classe: "4A", room: "-", percorso: "🍷" },
    { id: 213, cognome: "NAVARRETTA", nome: "Alexis Denis Fabien", classe: "4A", room: "123", percorso: "🍷" },
    { id: 214, cognome: "OBERTO", nome: "Debora", classe: "4A", room: "210", percorso: "🍷" },
    { id: 215, cognome: "TAPPELLA", nome: "Luca", classe: "4A", room: "116", percorso: "🍴" },
    { id: 216, cognome: "TESSARIN", nome: "Sharon", classe: "4A", room: "205", percorso: "🍴" },
    { id: 217, cognome: "VIOT", nome: "Cecilia", classe: "4A", room: "210", percorso: "🍷" },
    { id: 218, cognome: "ZHU", nome: "Fabio Junjie", classe: "4A", room: "-", percorso: "🍷" },

    // Classe 4B
    { id: 219, cognome: "BADERY", nome: "Michelle", classe: "4B", room: "-", percorso: "🍴" },
    { id: 220, cognome: "CAMPANALE", nome: "Aronne", classe: "4B", room: "-", percorso: "🍷" },
    { id: 221, cognome: "CHESSA", nome: "Samuele", classe: "4B", room: "111", percorso: "🍴" },
    { id: 222, cognome: "CHEVRERE", nome: "Cloe", classe: "4B", room: "-", percorso: "🍴" },
    { id: 223, cognome: "COLLURA", nome: "Asia Francesca", classe: "4B", room: "-", percorso: "🍷" },
    { id: 224, cognome: "COSTABLOZ", nome: "Giulia", classe: "4B", room: "-", percorso: "🍷" },
    { id: 225, cognome: "DEPLANO", nome: "Alessandro Antoine Junior", classe: "4B", room: "-", percorso: "🍷" },
    { id: 226, cognome: "FAVRE", nome: "Emilie", classe: "4B", room: "217", percorso: "🍷" },
    { id: 227, cognome: "GEMELLO", nome: "Leonardo", classe: "4B", room: "-", percorso: "🍴" },
    { id: 228, cognome: "GIARDULLO", nome: "Christian", classe: "4B", room: "-", percorso: "🍴" },
    { id: 229, cognome: "GIOVANNELLI T", nome: "Tommaso", classe: "4B", room: "113", percorso: "🍷" },
    { id: 230, cognome: "GORREX", nome: "Valerie", classe: "4B", room: "212", percorso: "🍴" },
    { id: 231, cognome: "HACHEMAOUI", nome: "Slimane Raffaello", classe: "4B", room: "117", percorso: "🍷" },
    { id: 232, cognome: "LANTERI", nome: "Paolo", classe: "4B", room: "-", percorso: "🍷" },
    { id: 233, cognome: "LODATO", nome: "Lorenzo Damiano", classe: "4B", room: "-", percorso: "🍴" },
    { id: 234, cognome: "MASCARO", nome: "Angelica", classe: "4B", room: "-", percorso: "🍴" },
    { id: 235, cognome: "MEYNET", nome: "Riccardo", classe: "4B", room: "123", percorso: "🍴" },
    { id: 236, cognome: "MILLESI", nome: "Aline", classe: "4B", room: "-", percorso: "🍷" },
    { id: 237, cognome: "NICOLASI", nome: "Ginevra", classe: "4B", room: "217", percorso: "🍴" },
    { id: 238, cognome: "NIZELLI", nome: "Luca", classe: "4B", room: "-", percorso: "🍴" },
    { id: 239, cognome: "PRIOD", nome: "Anaïs", classe: "4B", room: "-", percorso: "🍴" },
    { id: 240, cognome: "SAVELLA", nome: "Ilaria", classe: "4B", room: "210", percorso: "🍷" },
    { id: 241, cognome: "SERIO", nome: "Federica", classe: "4B", room: "217", percorso: "🍷" },
    { id: 242, cognome: "VOUT", nome: "Sophie", classe: "4B", room: "-", percorso: "🍷" },
    { id: 243, cognome: "VUILLERMOZ", nome: "Asia", classe: "4B", room: "-", percorso: "🍷" },

    // Classe 5A
    { id: 244, cognome: "AGOSTINO", nome: "Thomas", classe: "5A", room: "-", percorso: "🍴", gruppo: "G2" },
    { id: 245, cognome: "BERNARDI", nome: "Caterina", classe: "5A", room: "-", percorso: "🍴", gruppo: "G2" },
    { id: 246, cognome: "BORRA", nome: "Yader", classe: "5A", room: "-", percorso: "🍴", gruppo: "G1" },
    { id: 247, cognome: "CARRUOZZO", nome: "Amalia", classe: "5A", room: "201", percorso: "🍴", gruppo: "G1" },
    { id: 248, cognome: "CELESIA A", nome: "Alessio", classe: "5A", room: "120", percorso: "🍴", gruppo: "G2" },
    { id: 249, cognome: "CHIALE", nome: "Alessio", classe: "5A", room: "-", percorso: "🍴", gruppo: "G2" },
    { id: 250, cognome: "DE GATTIS", nome: "Eleonora", classe: "5A", room: "219", percorso: "🍴", gruppo: "G2" },
    { id: 251, cognome: "FARINET", nome: "Luca", classe: "5A", room: "-", percorso: "🍴", gruppo: "G2" },
    { id: 252, cognome: "FORESTIERO", nome: "Simone", classe: "5A", room: "-", percorso: "🍴", gruppo: "G1" },
    { id: 253, cognome: "FOUDON", nome: "Emil", classe: "5A", room: "-", percorso: "🍴", gruppo: "G1" },
    { id: 254, cognome: "GLAVINAZ", nome: "Pierre", classe: "5A", room: "-", percorso: "🍴", gruppo: "G2" },
    { id: 255, cognome: "JOLY", nome: "Simone", classe: "5A", room: "-", percorso: "🍴", gruppo: "G1" },
    { id: 256, cognome: "MARASCO", nome: "Teresa", classe: "5A", room: "-", percorso: "🍴", gruppo: "G1" },
    { id: 257, cognome: "MARTINOD", nome: "Gabriel", classe: "5A", room: "-", percorso: "🍴", gruppo: "G1" },
    { id: 258, cognome: "OBERT", nome: "Tommy", classe: "5A", room: "125", percorso: "🍴", gruppo: "G2" },
    { id: 259, cognome: "PETRIS", nome: "Maurizio", classe: "5A", room: "113", percorso: "🍴", gruppo: "G2" },
    { id: 260, cognome: "PICCOLI", nome: "Greta", classe: "5A", room: "201", percorso: "🍴", gruppo: "G1" },
    { id: 261, cognome: "PIGNATELLI", nome: "Maria Vittoria", classe: "5A", room: "201", percorso: "🍴", gruppo: "G1" },
    { id: 262, cognome: "RASO", nome: "Beatrice", classe: "5A", room: "220", percorso: "🍴", gruppo: "G2" },
    { id: 263, cognome: "SALVADORI", nome: "Emile", classe: "5A", room: "124", percorso: "🍴", gruppo: "G2" },
    { id: 264, cognome: "SORRENTI", nome: "Gabriele", classe: "5A", room: "120", percorso: "🍴", gruppo: "G1" },
    { id: 265, cognome: "SPALLA", nome: "Giovanni", classe: "5A", room: "-", percorso: "🍴", gruppo: "G1" },
    { id: 266, cognome: "VALLOMY", nome: "Etienne", classe: "5A", room: "124", percorso: "🍴", gruppo: "G2" },
    { id: 267, cognome: "VIGLIANO", nome: "Jacopo", classe: "5A", room: "120", percorso: "🍴", gruppo: "G1" },

    // Classe 5B
    { id: 268, cognome: "CARRUOZZO", nome: "Virginia", classe: "5B", room: "-", percorso: "🍷", gruppo: "G2" },
    { id: 269, cognome: "CHREIM", nome: "Khadijé", classe: "5B", room: "221", percorso: "🍷", gruppo: "G1" },
    { id: 270, cognome: "CORVO", nome: "Filippo", classe: "5B", room: "119", percorso: "🍷", gruppo: "G1" },
    { id: 271, cognome: "COTTINO", nome: "Jacqueline", classe: "5B", room: "219", percorso: "🍷", gruppo: "G2" },
    { id: 272, cognome: "DORIGO", nome: "Lisa", classe: "5B", room: "-", percorso: "🍷", gruppo: "G1" },
    { id: 273, cognome: "HU", nome: "Jia Hao", classe: "5B", room: "-", percorso: "🍷", gruppo: "G2" },
    { id: 274, cognome: "JOLY", nome: "Daiana", classe: "5B", room: "-", percorso: "🍷", gruppo: "G1" },
    { id: 275, cognome: "KOUROUMA", nome: "Nora", classe: "5B", room: "215", percorso: "🍷", gruppo: "G2" },
    { id: 276, cognome: "LINTY", nome: "Alys", classe: "5B", room: "216", percorso: "🍷", gruppo: "G1" },
    { id: 277, cognome: "MARGUERETTAZ", nome: "Greta", classe: "5B", room: "221", percorso: "🍷", gruppo: "G2" },
    { id: 278, cognome: "MILLERY", nome: "Mathieu", classe: "5B", room: "124", percorso: "🍷", gruppo: "G2" },
    { id: 279, cognome: "PERNET", nome: "Pietro", classe: "5B", room: "-", percorso: "🍷", gruppo: "G1" },
    { id: 280, cognome: "RABAGLIO", nome: "Filippo", classe: "5B", room: "119", percorso: "🍷", gruppo: "G1" },
    { id: 281, cognome: "SECCO", nome: "Sofia", classe: "5B", room: "-", percorso: "🍷", gruppo: "G2" },
    { id: 282, cognome: "TAVERNA", nome: "Marta", classe: "5B", room: "-", percorso: "🍷", gruppo: "G1" },
    { id: 283, cognome: "TOMASELLA", nome: "Vittorio", classe: "5B", room: "-", percorso: "🍷", gruppo: "G2" }
]; 
