name: Deploy Rooming CLOUD

on:
  push:
    branches:
      - main  # Assicurati che il tuo branch principale si chiami 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Inserimento API Key Segreta
        run: |
          # Sostituisce il segnaposto nel file index.html con il valore reale salvato nei Secrets
          sed -i 's/FIREBASE_API_KEY_PLACEHOLDER/${{ secrets.FIREBASE_API_KEY }}/g' index.html

      - name: Pubblicazione su GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . 
          branch: gh-pages # GitHub creerà questo branch automaticamente per ospitare il sito
