name: Deploy Rooming CLOUD 

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Inserimento API Key Segreta
        run: |
          sed -i 's/FIREBASE_API_KEY_PLACEHOLDER/${{ secrets.FIREBASE_API_KEY }}/g' roomcloud.html
          
      - name: Pubblicazione su GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . 
          branch: gh-pages
